import React from 'react';

const Info = () => {
  return (
    <div className="data">
      <h4>Creation Process</h4>
        <p>Each piece is generated by an algorithm.
          The first step is to create a boundary and random points for the image. 
          I did this by using a implementation of a quadTree.<br></br><br></br>
          The next step is to pick a color for the piece. This was done by picking
          a random HSV value. Along with this I used binary search on a lookup table
          to match the HSV value with a color name.<br></br><br></br>
          The art itself is generated by drawing a series of fractal trees varying in
          thickness, rotation, and size.
        </p>
        <h5>Name Generation</h5>
        <p>The title of each piece is generated by artifical intelligence. <br></br>
        <br></br> The assigned color names were used as part of a promt to <a href="https://beta.openai.com/playground">OPENAI GPT-3 Model, Curie Engine</a> 
        , which then comes up with unique titles for each piece.
        </p>
    </div>
  )
}

export default Info;